fix: count just the right number of row
moleculerjs/moleculer-db pull request #304
Opened 2022-01-10 13:54 UTC by DenisFerrero

Apply a more explicit count of data for the pagination, normally there's no problem but when doing an ```include``` in the default scope will be counted the included data for each record. For example:

By having those two models

```js
let User = sequelize.define("users",
    {
      id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
      username: { type: DataTypes.STRING }
    }, { paranoid: true }
);
```

```js
let Auth = sequelize.define("auths",
    {
      id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
      name: { type: DataTypes.STRING }
    }, { paranoid: false }
);
```

and they have a relation like this

```js
Auth.belongsTo(models["users"], {
  foreignKey: "user_id",
  as: "users"
});
```

When trying to get all users with this defaultScope

```js
User.associate = function (models) {
    User.addScope("defaultScope", {
      include: [{
        model: models["auths"],
        as: "auths"
      }]
    });
};
```

The count value is equal to the number of auths that are related to each user returned.

See this [SandBox](https://codesandbox.io/s/moleculer-pagination-not-working-correctly-hm4jo) for a working sample.
 
Fix for #302

2022-01-10 18:03 UTC, icebob requested changes
Great, thanks. Please add relevant tests as well.

2022-01-11 13:15 UTC, DenisFerrero commented
I'm not really into tests but I did my best to understand how to do that. Is it okay or do I need to explicit something else?

2022-01-16 17:00 UTC, icebob reviewed
Thanks, it works with older sequelize versions, as well?

2022-01-17 08:05 UTC, DenisFerrero commented
Don't tested, but I found from the Sequelize docs that the feature that I have applied (```{ distinct: true, col: colName }```) is available since Sequelize v3. Below the links to the docs of each version:
- [Version 6](https://sequelize.org/v6/class/lib/model.js~Model.html#static-method-count)
- [Version 5](https://sequelize.org/v5/class/lib/model.js~Model.html#static-method-count)
- [Version 4](https://sequelize.org/v4/class/lib/model.js~Model.html#static-method-count)
- [Version 3](https://sequelize.org/v3/api/model/#countoptions-promiseinteger)

They wrote that if an ```include``` is provided this logic for filter the PK should be automatically applied but I think they didn't have tested using a ```defaulScope``` yet

2022-01-17 14:51 UTC, icebob commented
Thank for your investigation.

2022-01-17 14:51 UTC, merged