Fix constructor signature of MongoDB adapter in TypeScript
moleculerjs/moleculer-db pull request #346
Opened 2023-01-25 15:04 UTC by ostracod

We ran into an issue in our TypeScript code when we tried to use moleculer-db-adapter-mongo 0.4.16, because the TypeScript signature did not match the JavaScript code.

2023-01-29 17:52 UTC, icebob requested changes
Thanks.

2023-01-29 17:52 UTC, icebob commented on packages/moleculer-db-adapter-mongo/package.json
> -  "version": "0.4.16",
please revert changes in package.json.

2023-01-29 19:50 UTC, ostracod commented on packages/moleculer-db-adapter-mongo/package.json
> -  "version": "0.4.16",
Sure thing.

2023-01-30 18:50 UTC, icebob approved these changes

2023-01-30 18:50 UTC, merged