Fix: populate param parsing
moleculerjs/moleculer-db pull request #394
Opened 2024-08-27 14:58 UTC by Freezystem

I just noticed that params used in the `getNativeVirtualPopulateQuery` weren't the sanitized ones.
So I've added a parameter to pass the sanitized params along with the context.

One question remains though: 
> Why are we not directly altering `ctx.params` from the context instead of passing a sanitized value along with the context in methods ? It would avoid passing an additional parameter and prevent mistaking original params for sanitized ones.

2024-11-05 09:33 UTC, Freezystem commented
@icebob Can I have your review and opinion on this one ? 🙇🏼

2025-02-03 17:15 UTC, icebob requested changes
Plz revert the changes of package-lock file.

2025-02-04 08:50 UTC, Freezystem commented
Actually my previous PR has migrated the lockfile version to v2. 
I've reverted this change and rollbacked it to v1.
Let me know if it's ok.

2025-02-04 10:09 UTC, icebob commented
Thanks, all good

2025-02-04 10:09 UTC, merged